### ISSUE TITLE
Gallery Field

### ISSUE THREAD

**Issue by jphms** [tbruckmaier/corcel-acf#1]
Hey mate, I can't seem to make a gallery field work. Can you give a practical example of it?

I assumed it would work the same as as a repeater, as it is basically a repeater for images. here is my code:

```php
$homepage = Page::slug('homepage')->first()->translate();
        $repeaterFields = $homepage->acf->gallery; // returns the serialized value: "a:2:{i:0;s:2:"31";i:1;s:2:"25";}"
        $repeaterFields = $homepage->acf->gallery(); // returns Generic
        $repeaterFields->first(); // Text::class ??
        $repeaterFields->first()->url; // http:// .... /?post_type=acf-field&p=4
```

What am I missing here?

**Comment by tbruckmaier** [comment]
Yeah, the gallery field was only half-finished, I was just waiting for someone to use it :) I just implemented the changes, it is included in the newest version https://github.com/tbruckmaier/corcel-acf/releases/tag/v1.2.0 Now you should get a `Collection` auf `Attachment` classes from `$homepage->acf->gallery`.

For future reference: unknown field types return a `Generic` class by default. This behaviour can be changed in the config, see here: https://github.com/tbruckmaier/corcel-acf#custom-field-classes

**Comment by jphms** [comment]
Ahh, that explains it. It is working fine now, thanks for the package, very useful!
