### ISSUE TITLE
Issue with Laravel 9.0

### ISSUE THREAD

**Issue by daankleijngeld** [tbruckmaier/corcel-acf#15]
We are not able to install the package on Laravel 9.0
Below is the error which we get:

Problem 1
    - p-andrey/tentacles 1.2 requires illuminate/support ^5.5|^6|^7 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - p-andrey/tentacles 1.3 requires illuminate/support ^5.5|^6|^7|^8.0 -> found illuminate/support[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - tbruckmaier/corcel-acf 1.7 requires p-andrey/tentacles ^1.2 -> satisfiable by p-andrey/tentacles[1.2, 1.3].
    - Root composer.json requires tbruckmaier/corcel-acf ^1.7 -> satisfiable by tbruckmaier/corcel-acf[1.7].

**Comment by tbruckmaier** [comment]
Thanks for reporting, I have stumbled upon this myself the other day.

`p-andrey/tentacles` seems to work just fine, it just needs its composer dependencies updated. I have created a pull request at https://github.com/p-andrey/tentacles/pull/1, once this is merged, I will create a new release.

In the meantime, you can probably reference my fork `p-andrey/tentacles` in your `composer.json`

**Comment by daankleijngeld** [comment]
@tbruckmaier he merged your pull request. Will you be able to create a new release?
Kind regards,
Daan

**Comment by tbruckmaier** [comment]
@daankleijngeld just added a new release, thanks for organizing!
