### ISSUE TITLE
Can't get it working, returns null

### ISSUE THREAD

**Issue by PiyushKumarDongre** [tbruckmaier/corcel-acf#18]
Hi,

Stumbled upon this package as replacement for Corcel-acf for Laravel9, corcel ^6.0.0

I have configured as in documentation, but not able to get it working.

- I have a custom field 'phone' in the Post
- What I have tried:

```php

use Tbruckmaier\Corcelacf\AcfTrait;
use Corcel\Model\Post as Corcel;

class WPPost2 extends Corcel
{
    use AcfTrait;
    protected $connection = 'wpsite2';
    protected $postType = 'post';

    public static function boot()
    {
        self::addAcfRelations([
            'phone' => [
                'key' => 'phone',
                'label' => 'Sub Title',
                'name' => 'sub_title',
                'type' => 'text',
            ],
        ]);
        parent::boot();
    }
}
```

## Retrieving data
- In the api.php
```php
Route::get('/wp2', function () {
    $posts = \App\Models\WPPost2::where('post_type', 'post')->find(7);    // finding by id
    return response()->json([
        "message" => $posts->acf_phone->value,
        ]);
    // return response()->json($posts);
});
```
**Output**: Attempt to read property "value" on null

- But with the same settings, I can read meta data for the post

```php
Route::get('/wp2', function () {
    $posts = \App\Models\WPPost2::where('post_type', 'post')->find(7);
    return response()->json([
          "message" => $posts->meta->where('meta_key',"phone")->pluck('value'),
        ]);
    // return response()->json($posts);
});
```

**Output**: 
```bash
{
	"message": [
		"+918159990794"
	]
}
```

What am I missing ?
Kindly help.

**Comment by tbruckmaier** [comment]
Hm good question, it seems you have done everything correctly.

To debug this issue, could you please post the output of:
```php
Route::get('/wp2', function () {
    $posts = \App\Models\WPPost2::where('post_type', 'post')->find(7);    // finding by id
    dd(
        $posts->acf,
        $posts->meta,
        \App\Models\WPPost2::getAcfRelations()
    );
});
```

**Comment by PiyushKumarDongre** [comment]
Thank you for the prompt response. Here is the output

![image](https://user-images.githubusercontent.com/114692175/199858908-4aa2626a-9370-47e4-8f70-00f143128609.png)

**Comment by tbruckmaier** [comment]
Hi, sorry for the delay. I did not consider which fields would show collapsed, so could you please provide another output:
```
Route::get('/wp2', function () {
    $posts = \App\Models\WPPost2::where('post_type', 'post')->find(7);    // finding by id
    dd(
        $posts->meta->toArray(),
    );
});
```

**Comment by PiyushKumarDongre** [comment]
Hi, was waiting for reply. Here is the received output

```bash
{
  "message": [
    {
      "meta_id": 6,
      "post_id": 7,
      "meta_key": "_edit_lock",
      "meta_value": "1667466639:1",
      "value": "1667466639:1"
    },
    {
      "meta_id": 7,
      "post_id": 7,
      "meta_key": "_pingme",
      "meta_value": "1",
      "value": "1"
    },
    {
      "meta_id": 8,
      "post_id": 7,
      "meta_key": "_encloseme",
      "meta_value": "1",
      "value": "1"
    },
    {
      "meta_id": 11,
      "post_id": 7,
      "meta_key": "_edit_last",
      "meta_value": "1",
      "value": "1"
    },
    {
      "meta_id": 12,
      "post_id": 7,
      "meta_key": "phone",
      "meta_value": "+918159990794",
      "value": "+918159990794"
    },
    {
      "meta_id": 13,
      "post_id": 7,
      "meta_key": "_phone",
      "meta_value": "field_63636dc9d7d3a",
      "value": "field_63636dc9d7d3a"
    },
    {
      "meta_id": 20,
      "post_id": 7,
      "meta_key": "_wp_page_template",
      "meta_value": "default",
      "value": "default"
    }
  ]
}
```

**Comment by tbruckmaier** [comment]
Hi, it seems that you have configured the acf fields in the database (that is why the field `phone` has an auto-generated field name `field_63636dc9d7d3a`). In that case, it is sufficient to add the acf relations like this. Any acf internal config (like the field key) is queries from the database (fyi, acf field configs are stored in the table `wp_posts`)
```php
use Tbruckmaier\Corcelacf\AcfTrait;
use Corcel\Model\Post as Corcel;

class WPPost2 extends Corcel
{
    use AcfTrait;
    protected $connection = 'wpsite2';
    protected $postType = 'post';

    public static function boot()
    {
        self::addAcfRelations(['phone']);
        parent::boot();
    }
```
See the documentation at https://github.com/tbruckmaier/corcel-acf#basic-usage

The way you have used the plugin (with the field config array) should only be used if you configure the acf fields in wordpress with ACF's php functions like `acf_add_local_field_group` (see https://github.com/tbruckmaier/corcel-acf#php-based-acf-config)

**Comment by PiyushKumarDongre** [comment]
Hi, Thanks for the response.
I have used ACF plugin to generate custom fields, don't know if it does this -> "configure the acf fields in wordpress with ACF's php functions like acf_add_local_field_group"

- Even with the above mentioned way of defining 'addAcfRelations', I am getting below responses.

- Model
```bash

use Tbruckmaier\Corcelacf\AcfTrait;
use Corcel\Model\Post as Corcel;

class WPPost2 extends Corcel
{
    use AcfTrait;
    protected $connection = 'wpsite2';
    protected $postType = 'post';

    public static function boot()
    {
        self::addAcfRelations(['phone']);
        parent::boot();
    }
}
```
- api endpoint
```bash
Route::get('/wp2', function () {
    $posts = \App\Models\WPPost2::find(7);
    return response()->json([
        // "message" => $posts->meta->toArray(),
        "message" => $posts->acf->phone(),

    ]);
});
```
- Output
```bash
{
  "message": null
}
```

**Comment by tbruckmaier** [comment]
Hi,

fyi, if you configure the ACF fields from the wordpress GUI, acf stores the field configs in the database. That is the default way and normally works fine. PHP-based config is a different approach, which you do not use at the moment.

In this default flow, corcel-acf fetches the field configs from the database, that is why you normally do not have to specify the field config in your application. Although in your case, corcel-acf apparently does not find the config in the database.

For a quickfix, you should be able to set the field config manually, with the correct field_key `field_63636dc9d7d3a` (the field key can be found in the post's meta data)

```php
use Tbruckmaier\Corcelacf\AcfTrait;
use Corcel\Model\Post as Corcel;

class WPPost2 extends Corcel
{
    use AcfTrait;
    protected $connection = 'wpsite2';
    protected $postType = 'post';

    public static function boot()
    {
        self::addAcfRelations([
            'phone' => [
                'key' => 'field_63636dc9d7d3a',
                'label' => 'Sub Title',
                'name' => 'sub_title',
                'type' => 'text',
            ],
        ]);
        parent::boot();
    }
```

This is of course not very practical, since you have to manually find out the auto-generated field key and specify them manually.

In order to use the "correct" way, please make sure that the field & field group have the correct name, and are published (in the wordpress ACF GUI)
If it still fails, you can manually investigate the database. The query below should return the saved acf field config (that is the query corcel-acf uses internally). If it does not find anything, there is something wrong with your database (or the plugin), and we have to further debug

```sql
SELECT *
FROM `wp_posts`
WHERE `post_type` = "acf-field"
  AND `wp_posts`.`post_name` = "field_63636dc9d7d3a"
  AND `wp_posts`.`post_name` IS NOT NULL
  AND EXISTS
    (SELECT *
     FROM `wp_posts` AS `wp_laravel_reserved_6`
     WHERE `wp_laravel_reserved_6`.`ID` = `wp_posts`.`post_parent`
       AND `post_status` IN ("publish",
                             "acf-disabled")
       AND `post_type` = "acf-field-group")
```

**Comment by PiyushKumarDongre** [comment]
Hi.
1. What should be the "correct name" for "field & field group" in ACF ?
I have this:

- Group
![image](https://user-images.githubusercontent.com/114692175/201304912-eb68ac2b-9349-45cb-b07c-d671836f7a32.png)

- Field
![image](https://user-images.githubusercontent.com/114692175/201304948-c012bc9b-873f-4aca-aad6-5c7aaedd568d.png)

2. Result from mysql query
![image](https://user-images.githubusercontent.com/114692175/201304017-febbf154-213a-4718-a7fa-57c610edcff0.png)

3. After adding below in WPPost2 model.

```php
 self::addAcfRelations([
            'phone' => [
                'key' => 'field_63636dc9d7d3a',
                'label' => 'Sub Title',
                'name' => 'sub_title',
                'type' => 'text',
            ],
        ]);
```
I still get a null.

**Comment by AntonCooper** [comment]
I was having the same issue. I think it might be something to do with the the property not being called correctly via Parasite. The callback gets registered, but when I call the property, the method name passed is 'hydrate'. I worked around this by using `$this->hasAcf('thumbnail')` to load the realtionships

**Comment by tbruckmaier** [comment]
Hi @AntonCooper @PiyushKumarDongre , I have just tagged a new version which should fix this issue and this package should work again as expected.

Minimum laravel version had to be raised to 7 (but v6, v7, v8 are EOL anyway). The tentacle package has been removed.

Hope it works!

**Comment by PKDmecom** [comment]
Hi,

Thanks it works now. Sorry to not be able to test it earlier and respond.

Have a nice day.
