### ISSUE TITLE
ACF PHP Generated Config File

### ISSUE THREAD

**Issue by matthewsuan** [tbruckmaier/corcel-acf#2]
hi @tbruckmaier ,

If I used a php generated acf config file, this wont work.

Do you have plans on adding support in the future?

TY

**Comment by matthewsuan** [comment]
I used the method getter instead. Worked fine.

**Comment by tbruckmaier** [comment]
Hi, sorry I somehow missed your issue. The php generated config is on the todo list, I have just not needed it. I will reopen this issue here as a reminder though. If anyone feels tempted to implement this, I would gladly accept PRs

**Comment by tbruckmaier** [comment]
PHP-based ACF config is now supported, instructions are in the readme!

**Comment by matthewsuan** [comment]
Hi @tbruckmaier thanks for this! I appreciate what you do.
