### ISSUE TITLE
Any plan for Laravel 10 ?

### ISSUE THREAD

**Issue by pkdwork1** [tbruckmaier/corcel-acf#20]
Hi,
Hope you are doing well.

I noticed that the package has dependency issues for Laravel 10. Is there any plan to support this version.

Regards

**Comment by tbruckmaier** [comment]
Hi @pkdwork1 ,

just tried to do the upgrade, but we have to wait until corcel itself supports laravel 10. See https://github.com/corcel/corcel/issues/631

**Comment by TechieToons** [comment]
Hey,
Can you please check, the core corcel has been updated to support Laravel 10.

Regards

**Comment by tbruckmaier** [comment]
Hi @TechieToons @pkdwork1 ,

I have just installed corcel-acf with laravel v10 & corcel v7 and everything seems to work fine so far. If you stumble upon any bugs, let me know. I will close this issue meanwhile
