### ISSUE TITLE
How to access relationship ACF fields?

### ISSUE THREAD

**Issue by zannix** [tbruckmaier/corcel-acf#21]
Hi, I'm switching over from outdated repo corcel/acf and I'm having trouble accessing "relationship" acf fields.

Namely, I used to access them like so (for an acf relationship called 'related_posts'):

`$post->acf->related_posts`

but using this package, it just returns null (even though I registered the relation in the boot method:

```
self::addAcfRelations([
    'related_posts',
]);
```

**Comment by zannix** [comment]
I did a bit of digging and if I dump the config array in Models/Post.php, getIsSerializedAttribute(), like so:

```
    public function getIsSerializedAttribute() : bool
    {
        dump($this->config);
        return !empty(Arr::get($this->config, 'multiple'));
    }
```

it outputs the following (no mention of "multiple" key):

```
array:14 [▼
  "aria-label" => ""
  "type" => "relationship"
  "instructions" => ""
  "required" => 0
  "conditional_logic" => 0
  "wrapper" => array:3 [▼
    "width" => ""
    "class" => ""
    "id" => ""
  ]
  "post_type" => array:1 [▶]
  "post_status" => array:1 [▼
    0 => "publish"
  ]
  "taxonomy" => ""
  "filters" => array:1 [▼
    0 => "search"
  ]
  "return_format" => "id"
  "min" => ""
  "max" => ""
  "elements" => ""
]
```

even though when dumping internal_value inside the getValueAttribute() method, it clearly outputs a serialized string:

`"a:1:{i:0;s:3:"125";}"`

**Comment by zannix** [comment]
Update, if I modify the getIsSerializedAttribute() method like this, it works:

```
   /**
     * Check if internal value is serialized
     *
     * @return bool
     */
    public function getIsSerializedAttribute() : bool
    {
        $value = $this->data->get($this->localKey);

        try {
            unserialize($value);
            return true;
        } catch (ErrorException $e) {
            return false;
        }
    }
```

**Comment by tbruckmaier** [comment]
Hi @zannix ,

thanks for your report! "relationship" was using the same behaviour as the "post_object" field type, which was indeed wrong (internal value of `post_object` is sometimes serialized depending on its `multiple` config, but `relationship` is *always* serialized as you have already mentioned).

Therfore, I have introduced a new internal clas `Relationship` for `relationship` acf fields, which should handle the internal value fine now. I have tagged a new release `1.10`.

I'll close this issue for now, feel free to reopen if you find any other bugs.

**Comment by zannix** [comment]
This seems to be working now, with the exception of trying to access a relationship which is empty, because then internal_value is set to empty string ("") and the method signature is expecting an array:

Tbruckmaier\Corcelacf\Models\BaseField::getSortedRelation(): Argument #2 ($ids) must be of type array, string given

**Comment by tbruckmaier** [comment]
Hi @zannix , thanks for noticing, should work now in 1.10.1

**Comment by zannix** [comment]
Confirmed relationships work as intended now. Thank you so much for your swift response and big thanks for upkeeping this package, it's of tremendous value.
