### ISSUE TITLE
Can't get all the sub fields of a repeater field

### ISSUE THREAD

**Issue by rezwanul7** [tbruckmaier/corcel-acf#3]
![image](https://user-images.githubusercontent.com/29156981/61707921-5922bc80-ad6d-11e9-9ac7-94aaa24a4cc0.png)

![image](https://user-images.githubusercontent.com/29156981/61707767-09dc8c00-ad6d-11e9-8a6f-a3ec26ac2d9a.png)

**Using dd( $page->acf->repeaters ); **
**Only field3 is showing, is there any way to solve this**

![image](https://user-images.githubusercontent.com/29156981/61707968-7a83a880-ad6d-11e9-9be8-053bf075b877.png)

**Comment by tbruckmaier** [comment]
Hi, this seems like a bug. Which version of ACF and laravel are you using?

**Comment by maxkopych** [comment]
I have similar issue. ACF-pro v5.5.11
Missing 1 field
![bug](https://user-images.githubusercontent.com/10473755/61939126-30aae600-af58-11e9-85c8-bf4c7e10be70.png)
![bug1](https://user-images.githubusercontent.com/10473755/61939127-30aae600-af58-11e9-9036-2af7f1aebe78.png)

**Comment by maxkopych** [comment]
@tbruckmaier The problem occurs when you have several fields with the same type go in a row. Then instead of pushing new field in collection it replacing last one.

**Comment by rezwanul7** [comment]
Just removing -keyB('type') from the repeater class solved my problem .

**Comment by maxkopych** [comment]
@rezwanul7 yeap it works. Thanks!

**Comment by tbruckmaier** [comment]
@rezwanul7 @maxkopych Nice, I just pushed a new release (1.2.2) with the fix included, seems to fix the bug. Could you report back if that release works for you?
