### ISSUE TITLE
how to loop through repeater?

### ISSUE THREAD

**Issue by jab1000** [tbruckmaier/corcel-acf#8]
Love that you now have L6/7 support and working to convert over from the old Corcel ACF.   The unknown for me is how do I loop through a repeater?

```$company['images'] = $company->acf->images;```

The line above does grab the "images repeater" which has 3 individual text/image fields in each one:
1.  image (image uploaded) (assuming I can get the different sizes like previous too)
2.  description (text area)
3.  URL (url / text)

With corcel ACF I just used a standard foreach in the blade to build an "image carousel" with those 3 items.
```
@foreach($images as $img)
$imgObj = $img['image']; 
$imgObj->size('gem_tf_750_375')
```

Thanks!

**Comment by tbruckmaier** [comment]
Hi, I am not sure if I completly understand your question or if there is anything wrong with the package? The way it /should/ work is as follows:

`$company->acf->images()` should return a `Tbruckmaier\Corcelacf\Models\Repeater` field, `$company->acf->images` or `$company->acf->images()->value()` a `Illuminate\Support\Collection`. 

This collection can be looped in blade as you suggested via `@foreach ($images as $img)`, each `$img` is a `Tbruckmaier\Corcelacf\Support\RepeaterLayout`. `RepeaterLayout` is a helper class to make accessing data easier, and can be used just as the base `->acf` method: `$img->description()` returns the `Tbruckmaier\Corcelacf\Models\Text` instance, `$img->description` the parsed text. Same goes for `$img->url` and `$img->image` (which returns an `Attachment` instance)

So I guess what you are looking for is something like this:

```blade
@foreach ($images as $img)
    <img src="{{ $img->image->size('foo') }}" />
    {{ $img->description }}
@endforeach
```

Does this answer your question? Or does it not work as described? In that case the recent changes for laravel 6 broke some things, and we need to investigate further

**Comment by jab1000** [comment]
thanks for the comment... I should have put what the exact error was for my code - sorry about that:

I have tried this a few different ways:
```
$company['images'] = $company->acf->images;
```
when I dump ```$company['images']``` it shows it as a "collection" of "Tbruckmaier repeater layouts"
```
Illuminate\Support\Collection {#1135 ▼
  #items: array:4 [▼
    0 => Tbruckmaier\Corcelacf\Support\RepeaterLayout
```
In the blade I try to use a foreach to loop through it but it throws this error:
```
Cannot use object of type Tbruckmaier\Corcelacf\Support\RepeaterLayout as array
```

I have also tried calling it a different way:
```
$company['images'] = $company->acf_images;

company "model" has:
use AcfTrait;
public static function boot()
{
	self::addAcfRelations(['images']);
	parent::boot();
}
```

When I use acf_images the dump is this format:
```Tbruckmaier\Corcelacf\Models\Repeater``` and when expanded the "data" shows ALL the ACF fields from the database for this "company post" (technically many more ACF fields).

Hopefully this all makes more sense - if not let me know what else is needed to make more sense.

Thanks!

**Comment by jab1000** [comment]
A few more items -- L6 but wanting to bump it to L7.  Since still L6 I am using Corcel V3 since V4 can't support L6.

When I use ```$company->acf->images()->value()``` I get this error:

"Too few arguments to function Illuminate\Database\Eloquent\Builder::value(), 0 passed in...."

**Comment by tbruckmaier** [comment]
> when I dump $company['images'] it shows it as a "collection" of "Tbruckmaier repeater layouts"

This is correct

> In the blade I try to use a foreach to loop through it but it throws this error:

Yep, `RepeaterLayout` is not iterable, it holds the content of one repeater item. You can see the data of each `RepeaterLayout` via `->getData()` or directly access a field via `->fieldname;`

```php
$company->acf->images; // Collection
foreach ($company->acf->images as $image) {
    dd($image); // RepeaterLayout
    dd($image->getData()); // Collection with fields of this repeater item: ['url' => 'xxx', 'image' => Attachment, ...]
    dd($image->url); // string
    dd($image->image); // Attachment
    // ...
}
``` 

> When I use $company->acf->images()->value() I get this error:
> "Too few arguments to function Illuminate\Database\Eloquent\Builder::value(), 0 passed in...."

Hm strange, this should return the same as `$company->acf->images`, and that is working in your case right?

**Comment by tbruckmaier** [comment]
I'm closing this for now, feel free to comment if you have any more issues
